version: '3.8'

services:
  # Party 0 服务
  party-0:
    build: .
    container_name: mpc-party-0
    ports:
      - "7080:7080"
    command: ["./demo-runner", "-index=0"]
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    volumes:
      - ./demos-go/cmd/threshold-ecdsa-web/certs:/app/certs
      - ./demos-go/cmd/threshold-ecdsa-web/config-0.yaml:/app/config-0.yaml

  # Party 1 服务
  party-1:
    build: .
    container_name: mpc-party-1
    ports:
      - "7081:7081"
    command: ["./demo-runner", "-index=1"]
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    volumes:
      - ./demos-go/cmd/threshold-ecdsa-web/certs:/app/certs
      - ./demos-go/cmd/threshold-ecdsa-web/config-1.yaml:/app/config-1.yaml

  # Party 2 服务
  party-2:
    build: .
    container_name: mpc-party-2
    ports:
      - "7082:7082"
    command: ["./demo-runner", "-index=2"]
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    volumes:
      - ./demos-go/cmd/threshold-ecdsa-web/certs:/app/certs
      - ./demos-go/cmd/threshold-ecdsa-web/config-2.yaml:/app/config-2.yaml

  # Party 3 服务
  party-3:
    build: .
    container_name: mpc-party-3
    ports:
      - "7083:7083"
    command: ["./demo-runner", "-index=3"]
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    volumes:
      - ./demos-go/cmd/threshold-ecdsa-web/certs:/app/certs
      - ./demos-go/cmd/threshold-ecdsa-web/config-3.yaml:/app/config-3.yaml

  # ETH客户端
  eth-client:
    build: .
    container_name: mpc-eth-client
    command: ["./eth-client"]
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    depends_on:
      - party-0
      - party-1
      - party-2
      - party-3

networks:
  default:
    name: mpc-network 