macro(set_xcode_property XCODE_PROPERTY XCODE_VALUE)
  if(IS_APPLE)
    set_property(TARGET ${TARGET} PROPERTY XCODE_ATTRIBUTE_${XCODE_PROPERTY}
                                           ${XCODE_VALUE})
  endif()
endmacro(set_xcode_property)

macro(configure_xcode_project TARGET_NAME)
  if(IS_APPLE)
    set_xcode_property(${TARGET_NAME} CODE_SIGN_IDENTITY "iPhone Developer")
    set_xcode_property(${TARGET_NAME} DEVELOPMENT_TEAM ${DEVELOPMENT_TEAM_ID})
    set_xcode_property(${TARGET_NAME} DYLIB_INSTALL_NAME_BASE @rpath)
    if(IS_IOS)
      set_xcode_property(${TARGET_NAME} ENABLE_BITCODE "YES")
    else()
      set_xcode_property(${TARGET_NAME} ENABLE_BITCODE "NO")
    endif()
  endif()
endmacro(configure_xcode_project)
